Project_1/project_1/Controllers/CartController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModelLayer;
using ModelLayer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace project_1.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<CartController> _logger;
        private StoreLevelPrograms _storeLevelPrograms;
        public CartController(StoreLevelPrograms storeLevelPrograms, ILogger<CartController> logger)
        {
            _storeLevelPrograms = storeLevelPrograms;
            _logger = logger;
        }
        // GET: CartController
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Based on the store picked the cart will be filled with what the user as selected at 
        /// said store. Total calualtions will be made so you know how much it is going to be
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ViewCart()
        {
            List<Cart> carts = new List<Cart>();
            List<Item> items = new List<Item>();
            carts = _storeLevelPrograms.GetCartItems(HttpContext.Session.GetString("Guid"));
            double total = 0;
            total = _storeLevelPrograms.CheckOutTotal(carts);
            ViewBag.total = total;
            return View(carts);
        }

        /// <summary>
        /// Based on the store picked the cart will be filled with what the user as selected at 
        /// said store. Total calualtions will be made so you know how much it is going to be
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult CheckOutCart(int id)
        {
            List<Cart> carts = new List<Cart>();
            carts = _storeLevelPrograms.GetCartItems(HttpContext.Session.GetString("Guid"));
            _storeLevelPrograms.CheckOutCounter(carts,id,HttpContext.Session.GetString("Guid"));
            return RedirectToAction("MainPage", "Home");
        }

        public ActionResult AddToCart(StoreViewModel svm)
        {
            _storeLevelPrograms.AddToCart(svm, HttpContext);
            return RedirectToAction("GetStoreInvertory","Store", new { id = svm.ID_store });
        }
    }
}

Project_1/project_1/Controllers/CustomerController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModelLayer;
using ModelLayer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace project_1.Controllers
{
    public class CustomerController : Controller
    {
        private StoreLevelPrograms _storeLevelPrograms1;
        private MapperClass _mapper;
        const string SessionID = "Guid";
        private readonly ILogger<CustomerController> _logger;
        public CustomerController(StoreLevelPrograms storeLevelPrograms, MapperClass map, ILogger<CustomerController> logger)
        {
            _storeLevelPrograms1 = storeLevelPrograms;
            _mapper = map;
            _logger = logger;
        }
        
        [HttpGet]
        public ActionResult CustomerLogin()
        {
            return View();
        }
        [HttpPost]
        [ActionName("CustomerLogin")]
        public async Task<IActionResult> CustomerLogin(CustomerViewModel customerViewModel)
        {
           
            var identity = _mapper.Authenticate(customerViewModel.firstName, customerViewModel.lastName);
            if(identity == null)
            {
                return RedirectToAction(nameof(CustomerLogin));
            }

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(identity),
                new AuthenticationProperties());
            Customer cus = _mapper.GetCustomer(customerViewModel.firstName, customerViewModel.lastName);
            HttpContext.Session.SetString(SessionID,cus.Customer_Id.ToString());

            return RedirectToAction("MainPage","Home");
        }
        [ActionName("Logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Guid");
            return RedirectToAction("Index","Home");
        }
    }
}

Project_1/project_1/Controllers/OrdersController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModelLayer;
using ModelLayer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace project_1.Controllers
{
    public class OrdersController : Controller
    {
        private StoreLevelPrograms _storeLevelPrograms;
        private MapperClass _mapper;
        private readonly ILogger<OrdersController> _logger;
        public OrdersController(StoreLevelPrograms storeLevelPrograms, MapperClass map, ILogger<OrdersController> logger)
        {
            _storeLevelPrograms = storeLevelPrograms;
            _mapper = map;
            _logger = logger;
        }


        /// <summary>
        /// This will show everything in the order. how many items, the price, total price, and 
        /// final total.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult FullOrderDetails(int id)
        {
            double total = 0;
            List<FullOrderViewModel> fullorder = new List<FullOrderViewModel>();
            fullorder = _storeLevelPrograms.GetFullOrderDetails(id);
            foreach(var num in fullorder)
            {
                total += (num.pricePaid * num.qtyOrdered);
            }
            ViewBag.total = total;
            return View("FullOrderViewModel", fullorder);
        }

        /// <summary>
        /// This will just get all the past orders of a customer and list them
        /// </summary>
        /// <returns></returns>
        public ActionResult AllPastOrders()
        {
            List<OrderViewModel> orderViewModels = new List<OrderViewModel>();
            List<Orders> orders = new List<Orders>();
            orders =  _storeLevelPrograms.AllPastOrders(HttpContext.Session.GetString("Guid"));
            foreach(var entry in orders)
            {
                orderViewModels.Add(_mapper.ConvertOrdersToOrderViewModel(entry));
            }

            return View(orderViewModels);
        }

        /// <summary>
        /// This will just get all the past orders of a store and list them
        /// </summary>
        /// <returns></returns>
        public ActionResult AllPastStoreOrders(int idStore)
        {
            List<OrderViewModel> orderViewModels = new List<OrderViewModel>();
            List<Orders> orders = new List<Orders>();
            orders = _storeLevelPrograms.AllPastStoreOrders(idStore);
            foreach (var entry in orders)
            {
                orderViewModels.Add(_mapper.ConvertOrdersToOrderViewModel(entry));
            }

            return View(orderViewModels);
        }
    }
}

Project_1/project_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kingdom Stores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">project_1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ol class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MainPage">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item" style="float:right!important">
                                <a class="nav-link text-dark" asp-controller="Customer" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item" style="float:right!important">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="AllPastOrders">Past Orders</a>
                            </li>
                            <li class="nav-item" style="float:right!important">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="ViewCart">Cart</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item" style="float:right!important">
                                <a class="nav-link text-dark" asp-controller="Customer" asp-action="CustomerLogin">Login</a>
                            </li>
                        }
                    </ol>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - project_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>